// Generated by build_app_renderer_bundle.mjs. Do not edit by hand.
(() => {
'use strict';
// Source: duration.js
const DRUM_NOTE_VALUES = Object.freeze([
  '1n',
  '2n',
  '4n',
  '8n',
  '16n',
  '32n',
]);

const DURATION_BY_VALUE = Object.freeze({
  '1n': 'w',
  '2n': 'h',
  '4n': 'q',
  '8n': '8',
  '16n': '16',
  '32n': '32',
});

function toVexFlowDuration(value, { rest = false } = {}) {
  const duration = DURATION_BY_VALUE[value];
  if (duration == null) {
    throw new Error(`Unsupported drum note value: ${String(value)}`);
  }
  return rest ? `${duration}r` : duration;
}

function isBeamableValue(value) {
  return value === '8n' || value === '16n' || value === '32n';
}


// Source: voice_mapping.js
const DRUM_VOICE_IDS = Object.freeze([
  'hihat',
  'ride',
  'crash',
  'snare',
  'tom1',
  'tom2',
  'floorTom',
  'kick',
]);

const DRUM_VOICE_MAP = Object.freeze({
  crash: Object.freeze({
    key: 'g/5',
    notehead: 'x',
    stemDirection: 1,
  }),
  ride: Object.freeze({
    key: 'f/5',
    notehead: 'x',
    stemDirection: 1,
  }),
  hihat: Object.freeze({
    key: 'e/5',
    notehead: 'x',
    stemDirection: 1,
  }),
  tom1: Object.freeze({
    key: 'd/5',
    notehead: 'normal',
    stemDirection: 1,
  }),
  snare: Object.freeze({
    key: 'c/5',
    notehead: 'normal',
    stemDirection: 1,
  }),
  tom2: Object.freeze({
    key: 'a/4',
    notehead: 'normal',
    stemDirection: 1,
  }),
  floorTom: Object.freeze({
    key: 'g/4',
    notehead: 'normal',
    stemDirection: -1,
  }),
  kick: Object.freeze({
    key: 'f/4',
    notehead: 'normal',
    stemDirection: -1,
  }),
});

function voiceMappingFor(voiceId) {
  const mapping = DRUM_VOICE_MAP[voiceId];
  if (mapping == null) {
    throw new Error(`Unknown drum voice: ${String(voiceId)}`);
  }
  return mapping;
}


// Source: document.js

const NOTE_VALUE_SET = new Set(DRUM_NOTE_VALUES);
const VOICE_ID_SET = new Set(DRUM_VOICE_IDS);
const DEFAULT_SUBDIVISION = '8n';

function parseDrumNotationDocument(input) {
  const raw = typeof input === 'string' ? JSON.parse(input) : input;
  assertObject(raw, 'document');
  if (!Array.isArray(raw.measures) || raw.measures.length === 0) {
    throw new Error('DrumNotationDocument.measures must be a non-empty array.');
  }

  return {
    subdivision: optionalNoteValue(raw.subdivision, 'subdivision') ?? DEFAULT_SUBDIVISION,
    measures: raw.measures.map(parseMeasure),
  };
}

function parseMeasure(rawMeasure, measureIndex) {
  assertObject(rawMeasure, `measures[${measureIndex}]`);
  if (!Array.isArray(rawMeasure.notes) || rawMeasure.notes.length === 0) {
    throw new Error(`measures[${measureIndex}].notes must be a non-empty array.`);
  }
  return {
    notes: rawMeasure.notes.map((rawNote, noteIndex) =>
      parseNote(rawNote, measureIndex, noteIndex),
    ),
  };
}

function parseNote(rawNote, measureIndex, noteIndex) {
  const path = `measures[${measureIndex}].notes[${noteIndex}]`;
  assertObject(rawNote, path);
  const value = optionalNoteValue(rawNote.value, `${path}.value`);
  const rest = rawNote.rest === true;
  const voices = rest ? [] : parseVoices(rawNote.voices, path);

  return {
    value,
    voices,
    rest,
    sticking: optionalString(rawNote.sticking, `${path}.sticking`),
    accent: rawNote.accent === true,
    flam: rawNote.flam === true,
    ghost: rawNote.ghost === true,
    tie: rawNote.tie === true,
  };
}

function optionalNoteValue(value, path) {
  if (value == null) return undefined;
  if (!NOTE_VALUE_SET.has(value)) {
    throw new Error(`${path} is unsupported: ${String(value)}`);
  }
  return value;
}

function parseVoices(rawVoices, path) {
  if (!Array.isArray(rawVoices) || rawVoices.length === 0) {
    throw new Error(`${path}.voices must be a non-empty array for notes.`);
  }
  return rawVoices.map((voice, index) => {
    if (!VOICE_ID_SET.has(voice)) {
      throw new Error(`${path}.voices[${index}] is unknown: ${String(voice)}`);
    }
    return voice;
  });
}

function optionalString(value, path) {
  if (value == null) return undefined;
  assertString(value, path);
  return value;
}

function assertObject(value, path) {
  if (value == null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${path} must be an object.`);
  }
}

function assertString(value, path) {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`${path} must be a non-empty string.`);
  }
}


// Source: renderer.js

const DEFAULT_RENDER_OPTIONS = Object.freeze({
  baseMeasureWidth: 640,
  measureWidth: null,
  staffX: 8,
  staffY: 10,
  staffHeight: 126,
  paddingRight: 12,
  formatterWidth: null,
  formatterWidthScale: 0.92,
  availableWidth: null,
  notesPerSystem: null,
  minNoteWidth: 39,
  systemEndReserve: 28,
  noteSpacing: 34,
  systemGapY: 140,
  finalRepeat: true,
  grouping: null,
  repeatClefEverySystem: true,
  standardAccents: true,
  stemMode: 'single',
  flatBeams: true,
});

function renderDrumNotationSvg(documentJson, options = {}) {
  return renderDrumNotationSvgWithMetadata(documentJson, options).svg;
}

function renderDrumNotationSvgWithMetadata(documentJson, options = {}) {
  const document = parseDrumNotationDocument(documentJson);
  const VF = options.vexFlow ?? resolveVexFlow();
  const renderOptions = resolveRenderOptions({ ...DEFAULT_RENDER_OPTIONS, ...options });
  const systems = notationSystemsForDocument(document, renderOptions);
  const systemCount = systems.length;
  const width =
    renderOptions.staffX +
    renderOptions.paddingRight +
    renderOptions.measureWidth;
  const height =
    renderOptions.staffY +
    renderOptions.staffHeight +
    Math.max(0, systemCount - 1) * renderOptions.systemGapY;

  const host = createDetachedHost();
  const renderer = new VF.Renderer(host, VF.Renderer.Backends.SVG);
  renderer.resize(width, height);
  const context = renderer.getContext();

  for (let index = 0; index < systems.length; index += 1) {
    const system = systems[index];
    const layout = systemLayoutForIndex(index, renderOptions);
    const stave = new VF.Stave(
      layout.x,
      layout.y,
      renderOptions.measureWidth,
    );
    if (layout.isSystemStart && renderOptions.repeatClefEverySystem) {
      stave.addClef('percussion');
    }
    if (renderOptions.finalRepeat === true && index === systems.length - 1) {
      setEndRepeatBar(VF, stave);
    }
    stave.setContext(context).draw();

    const notes = system.entries.map((entry) =>
      createVexFlowNote(VF, resolvedNoteForEntry(entry, document), {
        stemMode: renderOptions.stemMode,
        metadata: entry,
        standardAccents: renderOptions.standardAccents,
      }),
    );
    const voice = new VF.Voice({
      num_beats: system.entries.length,
      beat_value: beatValueForSystem(system),
    }).setStrict(false);
    voice.addTickables(notes);
    const formatterWidth = formatterWidthForSystem(system, renderOptions);
    new VF.Formatter()
      .joinVoices([voice])
      .format([voice], formatterWidth);
    const beams = createBeams(
      VF,
      notes,
      system,
      renderOptions,
    );
    voice.draw(context, stave);
    drawBeams(context, beams);
  }

  return {
    svg: extractSvg(host),
    notes: systems.flatMap((system) => system.entries.map(noteMetadataForEntry)),
  };
}

function createVexFlowNote(VF, note, options = {}) {
  const duration = toVexFlowDuration(note.value, { rest: note.rest });
  const mappings = note.rest ? [] : note.voices.map(voiceMappingFor);
  const keys = note.rest ? ['b/4'] : mappings.map((mapping) => mapping.key);
  const noteOptions = {
    keys,
    duration,
    stem_direction: stemDirectionForMappings(mappings, options.stemMode),
  };
  const noteheadType = noteheadTypeForMappings(mappings);
  if (noteheadType != null) {
    noteOptions.type = noteheadType;
  }
  const staveNote = new VF.StaveNote(noteOptions);

  applyNoteheads(VF, staveNote, mappings);
  attachSticking(VF, staveNote, stickingLabelFor(note));
  if (options.standardAccents !== false) {
    attachAccent(VF, staveNote, note.accent);
  } else if (note.accent && (note.sticking == null || note.sticking === '')) {
    attachAccentAnnotation(VF, staveNote, true);
  }
  attachGhost(VF, staveNote, note.ghost);
  attachFlam(VF, staveNote, note);
  attachNoteMetadata(staveNote, options.metadata);
  return staveNote;
}

function attachSticking(VF, staveNote, sticking) {
  if (sticking == null || sticking === '') return;
  const annotation = new VF.Annotation(sticking)
    .setFont('Arial', 12, '')
    .setVerticalJustification(VF.Annotation.VerticalJustify.BOTTOM);
  staveNote.addModifier(annotation, 0);
}

function attachAccent(VF, staveNote, accent) {
  if (!accent) return;
  attachAccentAnnotation(VF, staveNote, accent);
}

function attachAccentAnnotation(VF, staveNote, accent) {
  if (!accent) return;
  const annotation = new VF.Annotation('>')
    .setFont('Arial', 14, 'bold')
    .setVerticalJustification(VF.Annotation.VerticalJustify.TOP);
  staveNote.addModifier(annotation, 0);
}

function attachGhost(VF, staveNote, ghost) {
  if (!ghost) return;
  if (typeof VF.Parenthesis !== 'function') {
    staveNote.__drumcabularyGhost = true;
    return;
  }
  const modifierPosition = VF.ModifierPosition ?? VF.Modifier?.Position;
  if (modifierPosition?.LEFT == null || modifierPosition?.RIGHT == null) {
    staveNote.__drumcabularyGhost = true;
    return;
  }
  staveNote.addModifier(new VF.Parenthesis(modifierPosition.LEFT), 0);
  staveNote.addModifier(new VF.Parenthesis(modifierPosition.RIGHT), 0);
  staveNote.__drumcabularyGhost = true;
}

function attachFlam(VF, staveNote, note) {
  if (!note.flam) return;
  if (typeof VF.GraceNote !== 'function' || typeof VF.GraceNoteGroup !== 'function') {
    staveNote.__drumcabularyFlam = true;
    return;
  }
  const voice = note.rest ? 'snare' : note.voices[0];
  const mapping = voiceMappingFor(voice);
  const grace = new VF.GraceNote({
    keys: [mapping.key],
    duration: '8',
    slash: true,
  });
  const graceNoteGroup = new VF.GraceNoteGroup([grace], true);
  if (typeof graceNoteGroup.beamNotes === 'function') {
    graceNoteGroup.beamNotes();
  }
  if (typeof graceNoteGroup.attach === 'function') {
    graceNoteGroup.attach(staveNote);
  } else if (typeof staveNote.addModifier === 'function') {
    staveNote.addModifier(graceNoteGroup, 0);
  } else {
    staveNote.__drumcabularyFlam = true;
    return;
  }
  staveNote.graceNoteGroup = graceNoteGroup;
}

function applyNoteheads(VF, staveNote, mappings) {
  mappings.forEach((mapping, index) => {
    if (mapping.notehead === 'x' && typeof staveNote.setKeyStyle === 'function') {
      staveNote.setKeyStyle(index, { fillStyle: 'black', strokeStyle: 'black' });
    }
    if (mapping.notehead === 'x' && typeof VF.GlyphNoteHead === 'function') {
      staveNote.__drumcabularyNoteheads ??= [];
      staveNote.__drumcabularyNoteheads[index] = 'x';
    }
  });
}

function noteheadTypeForMappings(mappings) {
  if (mappings.length === 0) return null;
  return mappings.every((mapping) => mapping.notehead === 'x') ? 'x' : null;
}

function stemDirectionForMappings(mappings, stemMode = 'single') {
  if (stemMode === 'single') return 1;
  if (mappings.length === 0) return 1;
  const hasDownStem = mappings.some((mapping) => mapping.stemDirection < 0);
  return hasDownStem ? -1 : 1;
}

function stickingLabelFor(note) {
  if (note.sticking == null || note.sticking === '') return note.sticking;
  return note.sticking;
}

function attachNoteMetadata(staveNote, metadata) {
  if (metadata == null) return;
  setElementAttribute(staveNote, 'data-drum-note-index', String(metadata.index));
  setElementAttribute(staveNote, 'data-drum-measure-index', String(metadata.measureIndex));
  setElementAttribute(
    staveNote,
    'data-drum-measure-note-index',
    String(metadata.measureNoteIndex),
  );
}

function setElementAttribute(element, name, value) {
  if (typeof element.setAttribute === 'function') {
    element.setAttribute(name, value);
  } else {
    element.attributes ??= {};
    element.attributes[name] = value;
  }
}

function createBeams(VF, vexNotes, system, options = {}) {
  if (typeof VF.Beam !== 'function') return [];
  const beams = [];
  let beamGroup = [];
  for (let index = 0; index < vexNotes.length; index += 1) {
    if (index > 0 && system.beamBreaks.has(index)) {
      addBeamGroup(VF, beams, beamGroup, options);
      beamGroup = [];
    }
    const currentStemDirection = vexNotes[index].options?.stem_direction;
    const previousStemDirection =
      beamGroup.length === 0
        ? currentStemDirection
        : beamGroup[beamGroup.length - 1].options?.stem_direction;
    if (
      !system.entries[index].note.rest &&
      isBeamableValue(system.entries[index].value) &&
      currentStemDirection === previousStemDirection
    ) {
      beamGroup.push(vexNotes[index]);
      continue;
    }
    addBeamGroup(VF, beams, beamGroup, options);
    beamGroup =
      !system.entries[index].note.rest &&
      isBeamableValue(system.entries[index].value)
        ? [vexNotes[index]]
        : [];
  }
  addBeamGroup(VF, beams, beamGroup, options);
  return beams;
}

function addBeamGroup(VF, beams, beamGroup, options) {
  if (beamGroup.length < 2) return;
  const beam = new VF.Beam(beamGroup);
  if (options.flatBeams === true && beam.render_options != null) {
    beam.render_options.flat_beams = true;
  }
  if (options.flatBeamOffset != null && beam.render_options != null) {
    beam.render_options.flat_beam_offset = options.flatBeamOffset;
  }
  beams.push(beam);
}

function drawBeams(context, beams) {
  beams.forEach((beam) => beam.setContext(context).draw());
}

function formatterWidthForSystem(system, options) {
  const widthForNotes =
    system.entries.length * options.noteSpacing + options.systemEndReserve;
  const maxWidth = options.formatterWidth ?? options.measureWidth;
  return Math.min(maxWidth, widthForNotes);
}

function setEndRepeatBar(VF, stave) {
  const repeatEnd =
    VF.BarlineType?.REPEAT_END ??
    VF.Barline?.type?.REPEAT_END ??
    VF.Barline?.type?.repeatEnd ??
    5;
  if (typeof stave.setEndBarType === 'function') {
    stave.setEndBarType(repeatEnd);
  }
}

function resolveRenderOptions(options) {
  const availableWidth = Number(options.availableWidth);
  const hasAvailableWidth = Number.isFinite(availableWidth) && availableWidth > 0;
  const usableWidth = hasAvailableWidth
    ? Math.max(180, availableWidth - options.staffX - options.paddingRight)
    : options.baseMeasureWidth;
  const measureWidth =
    options.measureWidth ??
    Math.floor(usableWidth);
  const formatterWidth =
    options.formatterWidth ??
    Math.floor(
      Math.max(120, measureWidth - options.systemEndReserve),
    );

  return {
    ...options,
    measureWidth,
    formatterWidth,
  };
}

function notationSystemsForDocument(document, options) {
  const entries = noteEntriesForDocument(document);
  const grouping = parseGrouping(options.grouping);
  const notesPerSystem = normalizedNotesPerSystem(options);
  if (notesPerSystem != null) {
    return systemsForEntries(entries, {
      grouping,
      notesPerSystem,
    });
  }

  return document.measures.map((measure, measureIndex) => {
    const measureEntries = entries.filter(
      (entry) => entry.measureIndex === measureIndex,
    );
    return systemForEntries(measureEntries, grouping);
  });
}

function normalizedNotesPerSystem(options) {
  if (options.notesPerSystem === 'auto') return autoNotesPerSystem(options);
  if (options.notesPerSystem == null && options.availableWidth != null) {
    return autoNotesPerSystem(options);
  }
  if (options.notesPerSystem == null) return null;

  const value = Number(options.notesPerSystem);
  if (!Number.isFinite(value) || value < 1) return null;
  return Math.floor(value);
}

function autoNotesPerSystem(options) {
  const minNoteWidth = Number(options.minNoteWidth);
  const formatterWidth = Number(options.formatterWidth);
  const safeMinNoteWidth =
    Number.isFinite(minNoteWidth) && minNoteWidth > 0 ? minNoteWidth : 22;
  const safeSystemWidth =
    Number.isFinite(formatterWidth) && formatterWidth > 0
      ? formatterWidth
      : Math.max(120, options.measureWidth - options.systemEndReserve);
  return Math.max(4, Math.floor(safeSystemWidth / safeMinNoteWidth));
}

function noteEntriesForDocument(document) {
  const entries = [];
  document.measures.forEach((measure, measureIndex) => {
    measure.notes.forEach((note, measureNoteIndex) => {
      entries.push({
        index: entries.length,
        measureIndex,
        measureNoteIndex,
        value: note.value ?? document.subdivision,
        note,
      });
    });
  });
  return entries;
}

function systemsForEntries(entries, options) {
  if (entries.length === 0) return [];
  if (options.grouping.length === 0) {
    const systems = [];
    for (let index = 0; index < entries.length; index += options.notesPerSystem) {
      systems.push(
        systemForEntries(entries.slice(index, index + options.notesPerSystem), []),
      );
    }
    return systems;
  }

  const groups = groupedEntries(entries, options.grouping);
  const systems = [];
  let current = [];
  for (const group of groups) {
    if (
      current.length > 0 &&
      current.length + group.length > options.notesPerSystem
    ) {
      systems.push(systemForEntries(current, options.grouping));
      current = [];
    }
    current.push(...group);
  }
  if (current.length > 0) systems.push(systemForEntries(current, options.grouping));
  return systems;
}

function groupedEntries(entries, grouping) {
  const groups = [];
  let index = 0;
  let groupingIndex = 0;
  while (index < entries.length) {
    const size = grouping[groupingIndex % grouping.length];
    groups.push(entries.slice(index, index + size));
    index += size;
    groupingIndex += 1;
  }
  return groups;
}

function systemForEntries(entries, grouping) {
  return {
    entries,
    beamBreaks: beamBreaksForEntries(entries, grouping),
  };
}

function beamBreaksForEntries(entries, grouping) {
  const breaks = new Set();
  if (grouping.length === 0) return breaks;
  let consumed = 0;
  let groupingIndex = 0;
  while (consumed < entries.length) {
    if (consumed > 0) breaks.add(consumed);
    consumed += grouping[groupingIndex % grouping.length];
    groupingIndex += 1;
  }
  return breaks;
}

function parseGrouping(grouping) {
  if (Array.isArray(grouping)) {
    return grouping
      .map((value) => Number(value))
      .filter((value) => Number.isInteger(value) && value > 0);
  }
  if (typeof grouping !== 'string') return [];
  const trimmed = grouping.trim();
  const parts = /^\d+$/.test(trimmed) ? [...trimmed] : trimmed.match(/\d+/g) ?? [];
  return parts
    .map((value) => Number(value))
    .filter((value) => Number.isInteger(value) && value > 0);
}

function noteMetadataForEntry(entry) {
  return {
    index: entry.index,
    measureIndex: entry.measureIndex,
    measureNoteIndex: entry.measureNoteIndex,
    value: entry.value,
    voices: entry.note.voices,
    rest: entry.note.rest,
    sticking: entry.note.sticking,
    accent: entry.note.accent,
    flam: entry.note.flam,
    ghost: entry.note.ghost,
    tie: entry.note.tie,
  };
}

function systemLayoutForIndex(index, options) {
  return {
    x: options.staffX,
    y: options.staffY + index * options.systemGapY,
    isSystemStart: true,
  };
}

function beatValueForSystem(system) {
  const firstValue = system.entries[0]?.value;
  if (firstValue == null) return 4;
  const match = /^(\d+)n$/.exec(firstValue);
  return match == null ? 4 : Number(match[1]);
}

function resolvedNoteForEntry(entry, document) {
  return {
    ...entry.note,
    value: entry.value ?? document.subdivision,
  };
}

function createDetachedHost() {
  if (typeof document !== 'undefined') {
    return document.createElement('div');
  }
  return {
    children: [],
    appendChild(child) {
      this.children.push(child);
    },
    querySelector(selector) {
      if (selector !== 'svg') return null;
      return this.children.find((child) => child?.tagName === 'svg') ?? null;
    },
  };
}

function extractSvg(host) {
  const svg = host.querySelector('svg');
  if (svg == null) {
    throw new Error('VexFlow did not produce an SVG element.');
  }
  return svg.outerHTML ?? String(svg);
}

function resolveVexFlow() {
  const globalVexFlow = globalThis.VexFlow ?? globalThis.Vex?.Flow ?? globalThis.VF;
  if (globalVexFlow == null) {
    throw new Error('VexFlow is required. Pass { vexFlow } or load Vex.Flow globally.');
  }
  return globalVexFlow;
}

if (typeof window !== 'undefined') {
  window.renderDrumNotationSvg = (documentJson, options) =>
    renderDrumNotationSvg(documentJson, options);
  window.renderDrumNotationSvgWithMetadata = (documentJson, options) =>
    renderDrumNotationSvgWithMetadata(documentJson, options);
}

})();
